# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Nikita Morozov
email: greatdraken@gmail.com
domain: greatdrake.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Personal webpage.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://greatdrake.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

#header:
#  pages:
#    - name: Home
#      slug: /
#    - name: Work
#    - name: Blog
footer:
  show_powered_by: true
  #contact:
  #  - name: Email
  #    value: greatdraken[at]gmail.com
  #    link: mailto:greatdraken@gmail.com
  follow:
    - type: twitter
      name: Twitter
      link: https://x.com/nvimorozov
      username: "@nvimorozov"
    - type: github
      name: GitHub
      link: https://github.com/GreatDrake
    #- name: Scholar
    #  link: https://scholar.google.com/citations?user=00WbaisAAAAJ&hl=en
     #- name: Scholar
     #  link: https://scholar.google.com/citations?user=00WbaisAAAAJ&hl=en 


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

